# Site settings
title: Full Stack Life
header-img: img/home-bg.png
email: alexcrisan2005@hotmail.com
copyright_name: alexcrisan
description: > # this means to ignore newlines until "baseurl:"
  My Journey With Full-Stack Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alexcrisan
learn_profile: alexcrisan
email_username: alexcrisan2005@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
